// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using portal_2.API.Data;

namespace portal_2.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181003164606_AddedBrokerIdToApps")]
    partial class AddedBrokerIdToApps
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("portal_2.API.Models.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apftnm");

                    b.Property<string>("Apltnm");

                    b.Property<int>("BrokerId");

                    b.Property<int>("CaseId");

                    b.Property<DateTime?>("Placed");

                    b.Property<string>("PolNo");

                    b.Property<string>("Status");

                    b.Property<DateTime?>("Submittd");

                    b.Property<decimal>("premium");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("portal_2.API.Models.Broker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Affiliate");

                    b.Property<string>("AltEmail");

                    b.Property<string>("AltPhone");

                    b.Property<string>("Branch");

                    b.Property<int>("BrokerTempId");

                    b.Property<string>("City");

                    b.Property<string>("Email");

                    b.Property<int>("EntityId");

                    b.Property<string>("Fstname");

                    b.Property<bool>("IsContracted");

                    b.Property<DateTime>("LastActive");

                    b.Property<string>("Lstname");

                    b.Property<DateTime>("ModifyWhen");

                    b.Property<int>("NpnId");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<int>("Phone");

                    b.Property<int>("PhoneExt");

                    b.Property<string>("Rbm");

                    b.Property<string>("State");

                    b.Property<string>("Username");

                    b.Property<int>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Brokers");
                });

            modelBuilder.Entity("portal_2.API.Models.App", b =>
                {
                    b.HasOne("portal_2.API.Models.Broker")
                        .WithMany("Apps")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
